# Generated by Django 4.0.5 on 2022-06-17 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('career', models.CharField(choices=[('ICCI', 'Ingenieria Civil en Informatica'), ('ICI', 'Ingenieria Civil Industrial')], max_length=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('waiting_price', models.FloatField(null=True)),
                ('waiting_amount', models.FloatField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.share')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unary', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('fixed_com', models.FloatField(null=True)),
                ('variabl_com', models.FloatField(null=True)),
                ('type_order', models.CharField(choices=[('B', 'comprador'), ('S', 'vendedor')], max_length=2)),
                ('vigency', models.DateTimeField(default=None)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.share')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.share'),
        ),
    ]
