# Generated by Django 4.0.5 on 2022-06-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('total', models.FloatField()),
                ('fixed_com', models.FloatField(null=True)),
                ('variabl_com', models.FloatField(null=True)),
                ('type_order', models.CharField(choices=[('B', 'comprador'), ('S', 'vendedor')], max_length=2)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('vigency', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.share')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_buy', models.CharField(max_length=15)),
                ('share_sell', models.CharField(max_length=15)),
                ('market_val', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='orderaccount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderaccount',
            name='share',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAccount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.transactiontable'),
        ),
    ]
