# Generated by Django 4.0.5 on 2022-06-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vigency',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
