# Generated by Django 4.0.5 on 2022-06-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_account_admin_account_career_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaccount',
            name='fixed_com',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='variabl_com',
            field=models.FloatField(null=True),
        ),
    ]
