# Generated by Django 4.0.5 on 2022-06-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_transaction_transactiontable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
