# Generated by Django 4.0.5 on 2022-07-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_transaction_used_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareaccount',
            name='code',
        ),
    ]
