# Generated by Django 4.0.5 on 2022-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_shareaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='annual_rent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='diary_rent',
            field=models.FloatField(null=True),
        ),
    ]
