# Generated by Django 4.0.5 on 2022-06-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_transaction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_order',
            field=models.CharField(choices=[('B', 'Compra'), ('S', 'Venta')], max_length=2),
        ),
    ]
