# Generated by Django 4.0.5 on 2022-06-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_orderaccount_fixed_com_orderaccount_variabl_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
