# Generated by Django 4.0.5 on 2022-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_account_is_blocked_account_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='days_vigency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='vigency',
            field=models.DateTimeField(default=None),
        ),
    ]
