# Generated by Django 4.0.5 on 2022-07-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_transactiontable_annual_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
