# Generated by Django 4.0.5 on 2022-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_start_date_order_transfer_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transfer_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
    ]
