# Generated by Django 4.0.5 on 2022-06-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_transfer_date_order_start_date_order_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.share'),
        ),
    ]
